services:
  minio:
    image: docker.io/bitnami/minio:2025
    container_name: bula-ai-minio-server
    hostname: bula-ai-minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - bula-network
    volumes:
      - "minio_data:/data"
      - "./secrets:/certs"
      - "./secrets/CAs:/certs/CAs"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS:-bulas, exames}
      - MINIO_SCHEME=${MINIO_SCHEME:-https}
      - MINIO_SKIP_CLIENT=yes

networks:
  bula-network:
    driver: bridge
    external: true

volumes:
  minio_data:
